### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-client-js#2]
We should be able to test the code without any existing webclient.

@lgrahl, do you know what the easiest way would be? Can we test client/server on a single machine?

Integration with Travis would also be welcome.

**Comment by lgrahl** [comment]
I have no experience with CIs and tests regarding code that needs to be executed in the browser. It's definitely possible to run the Python server on loopback as long as Travis CI allows it. There should also be tests which are hard to provoke on a 'live' server. However, focus should probably be on automatic 'interop' tests for now.

**Comment by dbrgn** [comment]
Integration tests using local test server work!
