### ISSUE TITLE
Dependency Handling

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-client-js#23]
Should we compile-in a copy of the msgpack and nacl libraries?

Pro:
- A single file distribution, simple installation
- Depending on how the packaging is done, saltyrtc will always use a known version of the required libraries, avoiding incompatibilities with other versions of the same library

Con:
- Larger file size
- Separate dependencies required to use
- Conflicts could be possible if the application using saltyrtc also brings along its own msgpack and/or nacl library

@lgrahl what do you think?

Alternatively we could also provide two distributions, a fat and a light one.

**Comment by lgrahl** [comment]
I really don't know how good the npm dependency system works.
Downloadable files for end-users should probably contain all required dependencies.
For developers who use npm for their project, defining a dependency to this package should be enough for npm to pull all required dependencies of this package as well, right?

**Comment by dbrgn** [comment]
Ah. For a npm distribution that is true.

There should be a download-and-include file for people that don't use npm though. I was talking about that version.

**Comment by lgrahl** [comment]
Ideally, we'd have a download page with a bunch of checkboxes to include/exclude dependencies:

Bundle with:
- [x] tweetnacl
- [x] msgpack

That would be some work though. :)

**Comment by lgrahl** [comment]
Although I'm pretty sure that there is a ready made solution for this somewhere in the vast entirety of the internet.

**Comment by lgrahl** [comment]
(This should be on our to do list for the saltyrtc.org website.)

**Comment by dbrgn** [comment]
I think this has been solved in the meantime.

We have polyfilled/non-polyfilled, ES5/ES6, minified/non-minified, local/npm distributions.
