### ISSUE TITLE
Reduce dist size

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-client-js#25]
See 9d5abca4b1e5fd47732c3174c2ca83f8eec2f423

**Comment by dbrgn** [comment]
One of the possibilities could be to use the babel-es2015-polyfill instead of the full version.

Maybe take some inspiration from chunked-dc-java.

**Comment by threema-danilo** [comment]
Let's just stop polyfilling 🙂 All the APIs we currently need should be standardized.
