### ISSUE TITLE
Validate sender byte

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-client-js#27]
The sender byte should always be validated.

Once the handshake is done, messages with a different sender byte should be dropped.

@lgrahl it's correct that they should be silently dropped, right?

**Comment by lgrahl** [comment]
**Responders** that receive messages from other responders should drop them (the server is faulty in this case but it's manageable for the clients) and log a warning.

**Initiators** that receive messages from responders should never drop them (unless a handover process has already been started). It may happen that a responder loses it's connection to the server and reconnects. In this case the new responder replaces the old responder after the client authentication has been completed. (At least this is the idea - it may be that this conflicts with some tasks. We will need to re-evaluate this procedure at some point.)

**Comment by dbrgn** [comment]
Should a peer drop messages from the server (source byte 0x00) after the handshake is done?

**Comment by dbrgn** [comment]
Probably not, because [send-error](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Protocol.md#send-error) messages can still occur, right?

**Comment by lgrahl** [comment]
Correct, they should not be dropped.
