### ISSUE TITLE
Allow usage of own signalling (& STUN/TURN) server

### ISSUE THREAD

**Issue by rugk** [saltyrtc/saltyrtc-client-js#32]
As a good server there is e.g. https://github.com/andyet/signalmaster.

Is it possible to use your own servers here?

**Comment by dbrgn** [comment]
You'll be able to use any STUN / TURN server that you like. Initiating the PeerConnection is not in the responsibility of SaltyRTC, you simply pass the connection to the library.

But SaltyRTC *is* a signaling server protocol (with this repository being the client library wrapper), so you cannot use another signaling server.

There's an example [here](https://github.com/saltyrtc/saltyrtc-client-js/blob/master/example.ts) but it might already be a bit outdated. I'll add documentation and examples once the API is stable. Right now we're still in initial development mode, so the API could change at any point.

**Comment by dbrgn** [comment]
A complete working example of creating a secure data channel with WebRTC + SaltyRTC can be found in the test suite: https://github.com/saltyrtc/saltyrtc-client-js/blob/ce9d2914d8d6f5c3a389633fafd6817b5126997f/tests/integration.spec.ts#L383-L426

**Comment by rugk** [comment]
Ah, thanks for the information. So you *have to* use a custom signalling server (and I assume there you can also specify which STUN/TURN server to use).

**Comment by dbrgn** [comment]
Yes, although STUN/TURN servers are specified by the client, not by the server.

**Comment by lgrahl** [comment]
I should add that every signalling solution for WebRTC is a custom solution. WebRTC intentionally does not define how signalling protocols need to look like (and so far we seem to be the only one that have E2EE support). This should not be confused with STUN/TURN as Danilo already mentioned that the signalling has nothing to do with STUN/TURN. See: http://www.html5rocks.com/en/tutorials/webrtc/infrastructure/turn.png
