### ISSUE TITLE
Update 'send-error' message

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-client-js#42]
Further information can be found [here](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Protocol.md#send-error-message)
Discussion in saltyrtc/saltyrtc-meta#19 and saltyrtc/saltyrtc-meta#40

**Comment by lgrahl** [comment]
The amount of messages to be cached is described [here](https://github.com/saltyrtc/saltyrtc-meta/blob/protocol-cleanup/Protocol.md#client-to-client-messages)

**Comment by lgrahl** [comment]
Repeating has been removed from the spec. A 'send-error' is not recoverable. I've added measures to prevent possible errors on handover.

**Comment by dbrgn** [comment]
Closed in favor of #14.
