### ISSUE TITLE
Client-to-Client Messages/Behaviour Changes

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-client-js#45]
[The 'drop-responder' message has been changed](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Protocol.md#drop-responder-message). An initiator MAY now add a _reason_ field to a 'drop-responder' message the server SHALL close the connection to the corresponding responder with. That field contains a close code described [here](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Protocol.md#close-code-enumeration)

When to use the reason field has been described [here](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Protocol.md#client-to-client-messages).

The ['close' message](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Protocol.md#close-message) has been added.

All WebRTC-related messages have been removed from the spec and will be moved into a separate task soon. I'll use a new branch for that.

**Comment by lgrahl** [comment]
[Inactive responders SHALL be dropped by the initiator](https://github.com/saltyrtc/saltyrtc-meta/commit/312878823300d84e5279dc9a46e16c58c12c77d8)

**Comment by lgrahl** [comment]
The cookie MUST be generated for each new peer (including peers that reuse addresses announced by `new-initiator` and `new-responder`). Basically, cookie, overflow number and sequence number are now in the peer scope.

Message repeating has been removed, see #42.

The [Tasks section](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Protocol.md#tasks) has been added. The `auth` message has a bunch of new fields for the tasks, see [here](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Protocol.md#auth-message).

**Comment by dbrgn** [comment]
- [ ] Update drop-responder
- [ ] Add close message
- [ ] Drop inactive responders
- [ ] Make sure to generate a new cookie for each peer
