### ISSUE TITLE
Configurable retry attempts and linear backoff

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-client-js#84]
Proposed for the Java version: https://github.com/saltyrtc/saltyrtc-client-java/pull/72

Do we need this here as well? Never seemed to be an issue for me, so I think it's already done under the hood in the browser (whereas the Java version often fails in eduroam networks).

**Comment by dbrgn** [comment]
I'd keep the current version (without configurable retry) unless it's an actual problem.
